version = 1

test_patterns = [
  "test/**",
  "**.spec.ts",
  "**.e2e.ts"
]

exclude_patterns = ["/dist/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]